const fablesList = [
{ name: "Doomsayer", text: "If 4 or more players live, each living player may publicly choose (once per game) that a player of their own alignment dies "},
{ name: "Angel", text: "Something bad might happen to whoever is most responsible for the death of a new player. "},
{ name: "Buddhist", text: "For the first 2 minutes of each day, veteran players may not talk "},
{ name: "Hell’s Librarian", text: "Something bad might happen to whoever talks when the Storyteller has asked for silence. "},
{ name: "Revolutionary", text: "2 neighboring players are known to be the same alignment. Once per game, 1 of them registers falsely "},
{ name: "Fiddler", text: "Once per game, the Demon secretly chooses an opposing player: all players choose which of these 2 players win. "},
{ name: "Toymaker", text: "The Demon may choose not to attack & must do this at least once per game. Evil players get normal starting info. "},
{ name: "Fibbin", text: "Once per game, 1 good player might get incorrect information. "},
{ name: "Duchess", text: "Each day, 3 players may choose to visit you. At night*, each visitor learns how many visitors are evil, but 1 gets false info "},
{ name: "Sentinel", text: "There might be 1 extra or 1 fewer Outsider in play. "},
{ name: "Spirit of Ivory", text: "There can't be more than 1 extra evil player. "},
{ name: "Djinn", text: "Use the Djinn's special rule. All players know what it is. "},
{ name: "Bootlegger", text: "This script has homebrew characters or rules "},
{ name: "Ferryman", text: "On the final day, all dead players regain their vote token. "},
{ name: "Gardener", text: "The Storyteller assigns 1 or more players' characters. "},
{ name: "Storm Catcher", text: "Name a good character. If in play, they can only die by execution, but evil players learn which player it is. "},
];