const travellersList = [
		{ name: "Scapegoat", text: "If a player of your alignment is executed, you might be executed instead. "},
		{ name: "Gunslinger", text: "Each day, after the 1st vote has been tallied, you may choose a player that voted: they die. "},
		{ name: "Begger", text: "You must use a vote token to vote. If a dead player gives you theirs, you learn their alignment. You are sober and healthy."},
		{ name: "Bureaucrat", text: "Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow. "},
		{ name: "Thief", text: "Each night, choose a player (not yourself): their vote counts negatively tomorrow. "},
		{ name: "Butcher", text: "Each day, after the 1st execution, you may nominate again. "},
		{ name: "Bone Collector", text: "Once per game, at night*, choose a dead player: they regain their ability until dusk. "},
		{ name: "Harlot", text: "Each night*, choose a living player: if they agree, you learn their character, but you both might die. "},
		{ name: "Barista", text: "Each night, until dusk, 1) a player becomes sober, healthy & gets true info, or 2) their ability works twice. They learn which "},
		{ name: "Deviant", text: "If you were funny today, you cannot die by exile. "},
		{ name: "Apprentice", text: "On your 1st night, you gain a Townsfolk ability (if good) or a Minion ability (if evil). "},
		{ name: "Matron", text: "Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private. "},
		{ name: "Voudon", text: "Only you & the dead can vote. They don't need a vote token to do so. A 50% majority isn't required. "},
		{ name: "Judge", text: "Once per game, if another player nominated, you may choose to force the current execution to pass or fail. "},
		{ name: "Bishop", text: "Only the Storyteller can nominate. At least 1 opposing player must be nominated each day. "},
		{ name: "Gangster", text: "Once per day, you may choose to kill an alive neighbor, if your other alive neighbor agrees. "},
		{ name: "Gnome", text: "All players start knowing a player of your alignment. You may choose to kill anyone who nominates them. "},
];
